# Generated by Django 4.2.1 on 2023-05-26 10:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xblog', '0001_initial'),
        ('xgallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='owner',
        ),
        migrations.AddField(
            model_name='gallery',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xblog.blog'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='update_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
