# Generated by Django 4.2.1 on 2023-05-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xgallery', '0002_remove_album_owner_gallery_blog_galleryitem_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
