# Generated by Django 3.2.19 on 2023-05-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xblog', '0001_initial'),
        ('xgallery', '0003_galleryitem_description_alter_galleryitem_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='images', to='xblog.Post'),
        ),
    ]
