# Generated by Django 4.2.2 on 2025-05-05 10:21

from django.db import migrations, models
import django.utils.timezone
import xgallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('xgallery', '0004_galleryitem_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='album',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='album',
            name='update_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to=xgallery.models.image_upload_path, width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='update_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
