name: Run Tests

on:
  push:
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
        matrix:
          python_version:
            - '3.9'
            - '3.10'
            - '3.11'
          django_version:
            - '<4'
            - '<5'
            - '>=5,<6'
          exclude:
            - python_version: "3.9"
              django_version: ">=5,<6"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Run tests with coverage
        run: |
          pytest --cov=xgallery --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
